import { useState } from 'react';
import Editor from './Editor';
import Preview from './Preview';
import Head from 'next/head'
const Markdown = () => {
    const [value, setValue] = useState<string>("");

    return (
        <>
            <Head>
                <title>Mark Down Editor</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <div className="markdown__container">
                <div className="col1">
                    <Editor value={value} setValue={setValue} />
                </div>
                <div className="col2">
                    <Preview value={value} />
                </div>
            </div>
        </> 
     );
}
 
export default Markdown;